[package]
name = "percentum"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2024"
description = "Percentage type sanity"
license = "MIT"
repository = "https://github.com/clarkmoody/percentum"

[features]
default = ["decimal"]
decimal = ["rust_decimal"]

[dependencies]
rust_decimal = { version = "1.36", optional = true }
